
CREATE DATABASE EVOL;

CREATE TABLE Usuarios
(
  RUT VARCHAR(12) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Direccion VARCHAR(255) NOT NULL
);

CREATE TABLE Medidores
(
  Codigo VARCHAR(20) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  FechaCreacion DATE NOT NULL,
  RUT VARCHAR(12),
  FOREIGN KEY (RUT) REFERENCES Usuarios(RUT)
);